### ISSUE TITLE
Missing Github Action to ensure that your project builds

### ISSUE THREAD

**Issue by thatosmk** [ThreeOne31/learnX#3]
Maybe have a look at https://dev.to/dyarleniber/setting-up-a-ci-cd-workflow-on-github-actions-for-a-react-app-with-github-pages-and-codecov-4hnp

**Comment by ThreeOne31** [comment]
github workflow has been added and the repo is deployed at https://threeone31.github.io/learnX/

**Comment by thatosmk** [comment]
Great work Champ.
